### ISSUE TITLE
Allow different orders in different parts?

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/eko#146]
we're currently not able to redo the IC analysis out of the box, since we can not increase the matching order without increasing simultaneously the evolution order (which now is in place). So maybe we should
- allow a different order in matching then evolution (to redo IC)
- allow a different order in beta function (to benchmark CT14lo)

this would introduce 3 orders for the 3 usages we have

What do you think? @giacomomagni @AleCandido

**Comment by AleCandido** [comment]
That things are getting complicated...

Going down this road we're approaching more and more the "new scales to be varied" pattern...

**Comment by giacomomagni** [comment]
I'm wondering if this is really needed or we can just wait someone to ask for these features ...
This will complicate the a bit the situation which is already intricate since we are adding `QED`, 
and give space to run eko with "inconsistent" settings. (For IC we used that option 
because we didn't want to wait for full N3LO, not because we believe this is better)

**Comment by felixhekhorn** [comment]
This is a generalization of #75

**Comment by felixhekhorn** [comment]
Moved to https://github.com/NNPDF/eko/wiki/List-of-Possible-Future-Features
