### ISSUE TITLE
Eko convert from old format to 0.12 

### ISSUE THREAD

**Issue by giacomomagni** [NNPDF/eko#214]
When trying to convert an eko produced with `0.10.0` I realised that the converted as it is right now is useless.
Stickily speaking the operator conversion went through (modulo a small bug [here](https://github.com/NNPDF/eko/blob/873dc2d3cf68c12058db80f067e5d4ef700fcf2c/src/eko/io/legacy.py#L117) ), but the new operator lack of all the metadata which are then needed, for instance in the new version of pineko. 

Since I'm able to provide these information, I still have all the runcards,I propose to use them in the conversion and save a new full fledge `0.12.0` eko.
This should also simplify the code since `PseudoOperator` and `PseudoTheory` will not be need anymore.

**Comment by AleCandido** [comment]
> (modulo a small bug [here](https://github.com/NNPDF/eko/blob/873dc2d3cf68c12058db80f067e5d4ef700fcf2c/src/eko/io/legacy.py#L117) )

If you know which is the bug, please open a PR and describe (or just describe it here, and I'll try to take care).

> Since I'm able to provide these information, I still have all the runcards,I propose to use them in the conversion and save a new full fledge `0.12.0` eko.

The conversion is pretty much happening there, apart for the runcards, that is happening in the dedicated module https://github.com/NNPDF/eko/blob/873dc2d3cf68c12058db80f067e5d4ef700fcf2c/src/eko/io/runcards.py#L247-L352.

If you need to customize options, of course the CLI is defined in `ekobox`, feel free to modify it as you believe is going to suit more your use case (that most likely is the typical one). I will review it, but if it is working for your operators and it is also useful, I expect to be useful also for everything else (I missed to test the *utility*, since it is a bit more cumbersome to test, but if you have a more refined idea, please provide tests for that).

Just notice that the internal structure is going to be slightly modified soon, exactly because of a few shortcomings that have been found by @andreab1997 while using the operators in `pineko`, see #205 
However, I do not expect it to break the API, and the internal structure is still slightly unstable, exactly because I'm collecting feedback from actual usage (including yours, if you have).

**Comment by felixhekhorn** [comment]
if this is still relevant please reopen
