### ISSUE TITLE
Running of alpha_em in `runcards.update`

### ISSUE THREAD

**Issue by AleCandido** [NNPDF/eko#239]
_Originally posted by @felixhekhorn in https://github.com/NNPDF/eko/issues/238#issuecomment-1495732624_

It is currently not possible to activate the running of $\alpha_{em}$ outside of `runcards.update`, i.e. with old-style theory cards.

**Comment by felixhekhorn** [comment]
@niclaurenti how much is this a problem? i.e. what do you do in real life? I guess the default is no running ... in short: should we worry or no?

**Comment by AleCandido** [comment]
In principle, this should not be used during actual PDF evolution: we decided that $\alpha$ evolution would have been inconsistent, and so we do not explicitly support it.
But since it has been implemented, we provide it as a library function. I see no issue in not exposing it through the runcard, since we are actively deciding to never use it.

**Comment by felixhekhorn** [comment]
Even fine to just close again ... since I touched that part in #238, I just wanted to mention it ...

**Comment by AleCandido** [comment]
Let's wait for @niclaurenti acknowledgement, and then we can close.

**Comment by niclaurenti** [comment]
> @niclaurenti how much is this a problem? i.e. what do you do in real life? I guess the default is no running ... in short: should we worry or no?

In this moment I'm not using the running of `alphaem` so it will not be a mess. I don't know if in the future will use it

**Comment by niclaurenti** [comment]
But I did't understand exactly why the running of alphaem is not accessible now

**Comment by felixhekhorn** [comment]
> But I did't understand exactly why the running of alphaem is not accessible now

Only from the old-style theory runcards - because here
https://github.com/NNPDF/eko/blob/8f0e3a7f8ec7fac91aa910f42bcf8d259f2815c1/src/eko/io/runcards.py#L291-L297
I'm not setting the `em_running` property:
https://github.com/NNPDF/eko/blob/8f0e3a7f8ec7fac91aa910f42bcf8d259f2815c1/src/eko/quantities/couplings.py#L32
(which by the way breaks again our no-default-rule - but, as already said, we can not keep that up most likely due to #145 )

**Comment by niclaurenti** [comment]
> > In this moment I'm not using the running of `alphaem` so it will not be a mess. I don't know if in the future will use it
> 
> Wait... don't you know? @niclaurenti
> 
> This was the beginning of the story, 1y ago, when we asked Christopher, Alessandro Vicini, and friends whether α was used running in the partonic cross-sections calculations, and they replied "never".
> 
> Fine to allow people to get the α evolution stand-alone, but which would be the context in which you know you will have to use a running electromagnetic coupling during PDF evolution? Or is it just a fully-hypothetical statement, with no actual use case currently known?

Ah ok. Sorry I misunderstood the meaning of the issue. I thought that it was no longer possible to use the alphaem running in eko.
I know that in the grids aem is fixed.

However, the reason I implemented it was mainly for benchmarking against apfel (I had a difference and I wanted to understand whether it was due to a bug or due to the running of alpha)
