### ISSUE TITLE
infinite error loop running evolve_pdfs

### ISSUE THREAD

**Issue by maadcoen** [NNPDF/eko#333]
I tried running some code (see below) based on the pdf.ipynb tutorial but found myself stuck in an infinite loop of errors when running evolve_pdfs. I'am using macOS 14.1.2 (Sonoma).

First it throws **eko.io.exceptions.OutputExistsError: myeko2.tar**, followed by **tarfile.ReadError: file could not be opened successfully**. This is repeated another time, and then it goes into repeating indefinitely 
**RuntimeError: An attempt has been made to start a new process before the current process has finished its bootstrapping phase.** See (part of) the detailed output [here](https://github.com/NNPDF/eko/files/13740796/output.txt)

```
import pathlib
import eko
from ekobox.cards import example
import lhapdf
from ekobox.evol_pdf import evolve_pdfs


th_card = example.theory()
op_card = example.operator()
# here we replace the grid with a very minimal one, to speed up the example
op_card.xgrid = eko.interpolation.XGrid([1e-3, 1e-2, 1e-1, 5e-1, 1.])
op_card.mugrid = [(10.,5), (100.,5)]
# set QCD LO evolution
th_card.orders = (1,0)


# choose a PDFs set as a boundary condition
pdf = lhapdf.mkPDF("NNPDF40_nnlo_as_01180")


# set a path to store the eko
path = pathlib.Path("./myeko2.tar")
# and delete it in case it is already present
path.unlink(missing_ok=True)


evolve_pdfs(
    [pdf],
    th_card,
    op_card,
    install=True,
    name="Evolved_PDF",
    store_path=path
)
```

**Comment by AleCandido** [comment]
I believe your error is an actually *infinite* loop, but rather a long one.

In order to evolve the PDF, one 4-dim operator is computed for each value of the scale `mu2` (aka `Q2`). In particular, I believe they are being computed in parallel, as you can see from the stack trace:
```py
  File "/Users/maadcoen/opt/anaconda3/envs/QCD_calculations/lib/python3.10/site-packages/eko/evolution_operator/__init__.py", line 972, in integrate
    with Pool(self.n_pools) as pool:
```
Moreover, it is parallelized over one of the internal 4-dim, so you're getting plenty of errors.

So, at some point it seems like your EKO disappeared, or it was in some kind of invalid state (and this error appeared twice, not yet sure why `tarfile.ReadError: file could not be opened successfully:
`).
After that, you started getting a slew of errors from all the various processes spawned in the computation.

I can propose you two attempts that may help to solve the problem immediately, even though I did not reproduce and properly debug it yet:
- remove the multiprocessing, limiting the number of cores in the options (just set it to 1):
    https://github.com/NNPDF/eko/blob/7ad9234f6f612dc5e9fb0f1f3126eec7e8450935/src/eko/io/runcards.py#L97-L98
    I consider unlikely that this will fix your problem, but 
- try to use the new runner, since the current version of EKO is still using the *legacy mode* for compatibility
    ```
    File "/Users/maadcoen/opt/anaconda3/envs/QCD_calculations/lib/python3.10/site-packages/eko/runner/legacy.py", line 98, in compute
    ```
    you could this adding to your script
    ```py
    import eko.runner
    from eko.runner.managed import solve

    eko.runner.solve = solve
    ```
    this one has some chances to improve the tar file handling out of the box

In general, I would also discourage from using the example cards. It's not a wrong approach, if you're just trying to run. But whenever you want to use it for something, it is better to dump the runcard, even the example one, and review the various options (since they can affect a lot the result).

**Comment by maadcoen** [comment]
Thanks a lot for the quick reply!

When you say "I believe your error is an actually infinite loop, but rather a long one." you mean a finite loop I assume? I tried letting the code run, but it just keeps going up to the point my terminal can not store all the errors and beyond. My last attempt took at least 10 minutes before I killed it.

Adding the line `op_card.configs.n_integration_cores = 1` resolved the the avalanche of RuntimeErrors, and made the code finish almost immediately producing the output:
```
LHAPDF 6.5.3 loading /opt/homebrew/Cellar/lhapdf/6.5.3/share/LHAPDF/NNPDF40_nnlo_as_01180/NNPDF40_nnlo_as_01180_0000.dat
NNPDF40_nnlo_as_01180 PDF set, member #0, version 1; LHAPDF ID = 331100
install_pdf Evolved_PDF
Overwriting old PDF installation
Thanks for using LHAPDF 6.5.3. Please make sure to cite the paper:
  Eur.Phys.J. C75 (2015) 3, 132  (http://arxiv.org/abs/1412.7420)
```

I am bit puzzled by the line saying `Overwriting old PDF installation` which appears regardless of whether the myeko2.tar file is present or not.

If I also tried using the new runner you suggested, but that doesn't seem to make any difference.

**Comment by AleCandido** [comment]
> If I also tried using the new runner you suggested, but that doesn't seem to make any difference.

Ok, this is great to hear. Better if both of them are working.
The main limitation of the legacy one should be the memory consumption, that gets worse with multiprocessing. But if you're not facing this problem, so much the better.

> Adding the line `op_card.configs.n_integration_cores = 1` resolved the the avalanche of RuntimeErrors, and made the code finish almost immediately producing the output:

This is even greater to hear :)

> I am bit puzzled by the line saying `Overwriting old PDF installation` which appears regardless of whether the myeko2.tar file is present or not.

This is expected, when you use `evolve_pdfs()` the EKO could be reused from a stored one, or just recomputed:
https://github.com/NNPDF/eko/blob/7ad9234f6f612dc5e9fb0f1f3126eec7e8450935/src/ekobox/evol_pdf.py#L51-L59
In the case of your script, you're never passing a `path=` parameter, so it is always recomputed (and it should be pretty fast, because you have a small x-grid).

The message is then caused by your `install=True` parameter, which instructs `evolve_pdfs()` to attempt the installation of the evolved PDF, and it overwrites the already present one (so, in a certain sense, `install=True` means also *forced* installation).

**Comment by maadcoen** [comment]
Hi!
I understood the "overwriting is LHAPDF related. Furthermore, I tried rerunning my code above again, and suddenly the errors have disappeared and everything runs fine. I don't understand what has changed, but maybe there was something on my own computer that interfered. I'll close the issue then. Thanks for the help!
