### ISSUE TITLE
Low Q2 EXPANDED alpha_s is broken.

### ISSUE THREAD

**Issue by giacomomagni** [NNPDF/eko#389]
I seems that alphas evolution with EXPANDED  solution is broken at very low Q2 from NLO and higher.

```python
import eko    
from ekobox.cards import  example
from eko.io.types import EvolutionMethod

tcard = example.theory()
tcard.order = (2,0)
for evmod in [
    EvolutionMethod.ITERATE_EXACT,
    EvolutionMethod.TRUNCATED,
]:
    print("Evolution method:",  evmod.value)
    print("Evolution order:",  str(tcard.order))
    evmod = eko.couplings.couplings_mod_ev(evmod)
    sc = eko.couplings.Couplings(
            tcard.couplings,
            tcard.order,
            evmod,
            masses=[(x.value) ** 2 for x in tcard.heavy.masses],
            hqm_scheme=tcard.heavy.masses_scheme,
            thresholds_ratios=[1,1,1],
        )

    for q2 in [0.03, 0.04]:
        print("q2: ", q2, "as: ",sc.a_s(q2))
```
Returns:

```
Evolution method: iterate-exact
Evolution order: (2, 0)
q2:  0.03 as: 386447.3190965184
q2:  0.04 as: 386447.3190965184
Evolution method: truncated
Evolution order: (2, 0)
q2:  0.03 as: nan
q2:  0.04 as: 23.626254462242528
```

Although this is might sound irrelevant, because Q2 is really low, if by chance an FKTable has such value you get all the values to be `nan`. 

We should at least return an error if this happens.

**Comment by giacomomagni** [comment]
The point which break is exactly here:

https://github.com/NNPDF/eko/blob/38cc28c5c6c646118b674a51023b7a816d1d080e/src/eko/couplings.py#L105

for too low values of Q2 this become negative. 
So the solution is to return and error and crash, otherwise we might fill ekos and fktables with nans.

**Comment by felixhekhorn** [comment]
Mmm ... not sure ... surely I would not classify this as bug: you give non-sense, you expect non-sense, you get non-sense.

> for too low values of Q2 this become negative.

This precisely defines $\Lambda_{QCD}$.

I'd say this is a feature and I'm tempted to close this as "will not be fixed".

Also from what I learned from @alecandido I think this is a pythonic attitude: a library accepts almost anything as input (and hopes it casts itself to the representation it needs) and just uses it as. It is the callers responsibility and not the libraries to do the sanity checks.

**Comment by alecandido** [comment]
> Also from what I learned from @alecandido I think this is a pythonic attitude: a library accepts almost anything as input (and hopes it casts itself to the representation it needs) and just uses it as. It is the callers responsibility and not the libraries to do the sanity checks.

Indeed. The Pythonic part is *duck typing*: you pretend an object behaves in a certain way, until it doesn't. In which case an error is raised. If no error is raised, then there is no reason you could not apply the function.

About sanity checks, instead, it is a general rule-of-thumb: if a function should check its arguments, every function will do it. Leading to a proliferation of checks, and parameters being checked multiple times (in the best case, it's just redundant, but if checks are not designed, you might generate errors just because of poor and incompatible conditions).
For this, you can rely on the types during static analysis (e.g. with Mypy) and other static tools (e.g. Pylint), and tests for runtime checks.
If a function is being tested for a purpose, then it is guaranteed and documented to be used for that. But it doesn't mean it's not going to work beyond that (but the user could be on its own for weird behaviors).

**Comment by giacomomagni** [comment]
> Mmm ... not sure ... surely I would not classify this as bug: you give non-sense, you expect non-sense, you get non-sense.
> 
> > for too low values of Q2 this become negative.
> 
> This precisely defines ΛQCD.
> 
> I'd say this is a feature and I'm tempted to close this as "will not be fixed".

The but is that I get Ekos and  then `FKTables` full of `nans` even for the other values... 
Now you can convert it to a pineappl issue if you prefer, but I spent two hours to understand if it was validphys fault or 
whatever fault because  few `FKTables` where returning nans. 

I'd have appreciated an error message or a warning :)

Indeed this is a well known behaviour, but still with the "exact" solution you get a numerical nonsense, 
here instead you get only nans.

**Comment by alecandido** [comment]
> Mmm ... not sure ... surely I would not classify this as bug: you give non-sense, you expect non-sense, you get non-sense.
> 
> > for too low values of Q2 this become negative.
> 
> This precisely defines

Fwiw, I tend to agree.

> I'd have appreciated an error message or a warning :)

I'd rather document it properly. This does not increase the complexity of the code.

`nan` is a valid float value, with its specific algebra (everything combined to `nan` becomes `nan`, essentially). If this is unsuitable for some other program, I'd rather suggest replacing `nan` with some other values in there, or raise an error. And do it as late as possible.
Using `nan` is not a problem on its own. But if it's a problem somewhere, it should be fixed there :)

**Comment by giacomomagni** [comment]
Fine to crash here, in Pineko or in pineappl ... As long as we crash before all the information is lost I'm happy.

**Comment by alecandido** [comment]
> Fine to crash here, in Pineko or in pineappl ... As long as we crash before all the information is lost I'm happy.

In principle, even in vp it's an option. If the information is not lost, as you said.

**Comment by Radonirinaunimi** [comment]
> The bug is that I get one eko and then an entire FKTable full of nans, even for the other Q2 values ...

The most important part is this one. If the `NaN` only appears at the very low $Q^2$ for which this behavior is expected, then everything is fine. But it proliferates to all the other bins for which $Q^2$ are large - at which point could be considered as a bug.

**Comment by giacomomagni** [comment]
> > The bug is that I get one eko and then an entire FKTable full of nans, even for the other Q2 values ...
> 
> The most important part is this one. If the `NaN` only appears at the very low Q2 for which this behavior is expected, then everything is fine. But it proliferates to all the other bins for which Q2 are large - at which point could be considered as a bug.

Indeed, to be clear, inside the eko `nans` are confined to the `q2` for which `alpha_s` is `nan` but as long as you use in the convolution then everything is gone.
I opened the issue here because I don't see how this eko can be meaningful, but, if you feel that is pineappl duty to crash, please move the discussion there.

**Comment by alecandido** [comment]
In principle, this is a plain bug, but not an EKO one.

If `nan`s are confined to certain Q2 slices, they should affect only those, since those Q2 slices are involved only in the evolution of the corresponding bins.

If `nan`s proliferate elsewhere, this is a bug in the EKO consumption, since operations that are not expected should have been executed.

I tend to believe that there should be `nan`s in places where they affect all the bins, like in the first threshold operator (connecting the fitting scale to the relevant matching). But it could also be just a bug in the way the EKO is consumed (not sure how, but it could be).

**Comment by felixhekhorn** [comment]
- if the NaN are restricted to a certain subset of operators I would consider that fine - and I expect it to be so (since all EKOs are computed independently); if that is not true, then there is a EKO bug
- if an FK table has a dynamic fact. scale and the NaNs propagate this way to the whole FK table it should be signalled there (when you know that) - if only certain bins get "NaN-ed" I would consider that fine

**Comment by giacomomagni** [comment]
I'm sure the other slices where correct, because replacing the `nan` slices with identities made it working again.  
The other fix was to replace `nan` also from the list of `alphas` passed to:

https://github.com/NNPDF/pineko/blob/e3aeba27c1dd328bebe4bd52c90e107a7cd9a1f2/src/pineko/evolve.py#L313-L320

I'm sure the second change was not enough to recover the correct behaviour, but non 100% it is strictly necessary.

**Comment by alecandido** [comment]
For alphas should be the same as for the operators: they are only used when needed.

@felixhekhorn classification seems extensive enough, so, even for this, you should be in one of the two situations described above.

**Comment by felixhekhorn** [comment]
eko is behaving as expected - the problem which raised the question was addressed in https://github.com/NNPDF/pineappl/commit/9ca3022ef8288b9360584ced5d78f6701f7667e9
